export type RoleProfileId = 'cashier' | 'senior_cashier' | 'waiter' | 'manager' | 'kitchen' | 'support_admin';

export type RoleProfile = {
  id: RoleProfileId;
  labelKey: string;
  permissionIds: string[];
};

// roleProfiles синхронизированы с canonicalRoleProfiles backend pilot-каталога.
export const roleProfiles: RoleProfile[] = [
  {
    id: 'cashier',
    labelKey: 'staff.roleProfiles.cashier',
    permissionIds: [
      'pos.employee_shift.open',
      'pos.employee_shift.close',
      'pos.employee_shift.view_current',
      'pos.employee_shift.recent',
      'pos.cash_session.open',
      'pos.cash_session.view_current',
      'pos.catalog.view',
      'pos.floor.view',
      'pos.menu.view',
      'pos.order.create',
      'pos.order.view',
      'pos.order.add_line',
      'pos.order.change_quantity',
      'pos.order.void_line',
      'pos.order.close',
      'pos.pricing.view',
      'pos.pricing.discount.apply',
      'pos.pricing.surcharge.apply',
      'pos.precheck.issue',
      'pos.precheck.view',
      'pos.precheck.reprint',
      'pos.payment.cash',
      'pos.payment.card.manual',
      'pos.check.view',
    ],
  },
  {
    id: 'senior_cashier',
    labelKey: 'staff.roleProfiles.senior_cashier',
    permissionIds: [
      'pos.employee_shift.open',
      'pos.employee_shift.close',
      'pos.employee_shift.view_current',
      'pos.employee_shift.recent',
      'pos.cash_session.open',
      'pos.cash_session.close',
      'pos.cash_session.view_current',
      'pos.catalog.view',
      'pos.floor.view',
      'pos.menu.view',
      'pos.order.create',
      'pos.order.view',
      'pos.order.add_line',
      'pos.order.change_quantity',
      'pos.order.void_line',
      'pos.order.close',
      'pos.pricing.view',
      'pos.pricing.discount.apply',
      'pos.pricing.surcharge.apply',
      'pos.precheck.issue',
      'pos.precheck.view',
      'pos.precheck.reprint',
      'pos.precheck.cancel.request',
      'pos.payment.cash',
      'pos.payment.card.manual',
      'pos.payment.refund',
      'pos.check.view',
      'pos.sync.view',
    ],
  },
  {
    id: 'waiter',
    labelKey: 'staff.roleProfiles.waiter',
    permissionIds: [
      'pos.employee_shift.open',
      'pos.employee_shift.close',
      'pos.employee_shift.view_current',
      'pos.employee_shift.recent',
      'pos.catalog.view',
      'pos.floor.view',
      'pos.menu.view',
      'pos.order.create',
      'pos.order.view',
      'pos.order.add_line',
      'pos.order.change_quantity',
      'pos.order.void_line',
      'pos.order.close',
      'pos.pricing.view',
      'pos.precheck.issue',
      'pos.precheck.view',
      'pos.precheck.reprint',
      'pos.check.view',
    ],
  },
  {
    id: 'manager',
    labelKey: 'staff.roleProfiles.manager',
    permissionIds: [
      'pos.employee_shift.open',
      'pos.employee_shift.close',
      'pos.employee_shift.view_current',
      'pos.employee_shift.recent',
      'pos.cash_session.open',
      'pos.cash_session.close',
      'pos.cash_session.view_current',
      'pos.cash_drawer.record_event',
      'pos.catalog.view',
      'pos.floor.view',
      'pos.menu.view',
      'pos.order.create',
      'pos.order.view',
      'pos.order.add_line',
      'pos.order.change_quantity',
      'pos.order.void_line',
      'pos.order.close',
      'pos.pricing.view',
      'pos.pricing.discount.apply',
      'pos.pricing.surcharge.apply',
      'pos.precheck.issue',
      'pos.precheck.view',
      'pos.precheck.reprint',
      'pos.precheck.cancel.request',
      'pos.precheck.cancel',
      'pos.payment.cash',
      'pos.payment.card.manual',
      'pos.payment.other',
      'pos.payment.refund',
      'pos.check.view',
      'pos.check.reprint',
      'pos.sync.view',
      'pos.sync.retry_failed',
    ],
  },
  {
    id: 'kitchen',
    labelKey: 'staff.roleProfiles.kitchen',
    permissionIds: [
      'pos.employee_shift.view_current',
      'pos.catalog.view',
      'pos.kitchen.view',
      'pos.kitchen.status.change',
      'pos.kitchen.catalog.view',
      'pos.kitchen.recipe.view',
      'pos.kitchen.recipe.suggest',
      'pos.kitchen.catalog.suggest',
      'pos.kitchen.stock.receipt',
      'pos.kitchen.stock.inventory_count',
      'pos.kitchen.stock.write_off',
      'pos.kitchen.production.complete',
      'pos.kitchen.stop_list.view',
      'pos.kitchen.stop_list.update',
    ],
  },
  {
    id: 'support_admin',
    labelKey: 'staff.roleProfiles.support_admin',
    permissionIds: [
      'pos.sync.view',
      'pos.sync.retry_failed',
    ],
  },
];

export const roleProfileById = new Map(roleProfiles.map((profile) => [profile.id, profile]));
