package postgres

import platformpg "cloud-backend/internal/platform/postgres"

// RequiredSchema returns implemented-now PostgreSQL objects used before Cloud HTTP starts.
func RequiredSchema() []platformpg.SchemaRequirement {
	return []platformpg.SchemaRequirement{
		{
			Table:         "schema_migrations",
			RequiredBy:    "postgres startup migration history",
			MigrationFile: "startup framework ensureSchemaMigrationsTable",
			Columns: []string{
				"version", "checksum_sha256", "status", "applied_at",
			},
		},
		{
			Table:         "db_runtime_versions",
			RequiredBy:    "postgres startup runtime version contract",
			MigrationFile: "startup framework ensureRuntimeVersionTable",
			Columns: []string{
				"module_name", "module_version", "schema_version", "checksum_sha256", "status", "applied_at", "updated_at",
			},
		},
		{
			Table:         "cloud_edge_event_receipts",
			RequiredBy:    "cloudsync postgres repository ReceiveEdgeEvent idempotent receipt storage",
			MigrationFile: "001_init.sql",
			Columns: []string{
				"id", "idempotency_key", "restaurant_id", "device_id", "command_id", "event_id", "edge_event_id",
				"event_type", "aggregate_type", "aggregate_id", "envelope_version", "occurred_at", "cloud_received_at",
				"raw_payload_sha256_hex", "created_at",
			},
			Indexes: []string{
				"cloud_edge_event_receipts_edge_event_key", "cloud_edge_event_receipts_event_type_received_at",
			},
		},
		{
			Table:         "cloud_edge_event_raw_payloads",
			RequiredBy:    "cloudsync postgres repository ReceiveEdgeEvent raw payload storage",
			MigrationFile: "001_init.sql",
			Columns: []string{
				"receipt_id", "raw_payload", "raw_payload_sha256_hex", "created_at",
			},
		},
		{
			Table:         "inbox_events",
			RequiredBy:    "ClickHouse async forwarder delivery queue without request-path ClickHouse writes",
			MigrationFile: "001_init.sql",
			Columns: []string{
				"id", "receipt_id", "idempotency_key", "tenant_id", "restaurant_id", "device_id", "employee_id",
				"command_id", "event_id", "edge_event_id", "event_type", "aggregate_type", "aggregate_id",
				"envelope_version", "occurred_at", "cloud_received_at", "raw_payload", "raw_payload_sha256_hex",
				"processed_for_olap", "olap_export_status", "olap_export_attempts", "olap_next_retry_at",
				"olap_locked_at", "olap_locked_by", "olap_processed_at", "olap_last_error", "created_at", "updated_at",
			},
			Indexes: []string{
				"inbox_events_event_unique", "inbox_events_olap_pending", "inbox_events_restaurant_received", "inbox_events_event_type_received",
			},
		},
		{
			Table:         "olap_export_checkpoints",
			RequiredBy:    "ClickHouse async forwarder checkpoint and retry observability",
			MigrationFile: "001_init.sql",
			Columns: []string{
				"id", "worker_id", "last_exported_inbox_id", "last_exported_event_id", "last_exported_at",
				"last_error", "consecutive_failures", "next_retry_at", "updated_at",
			},
		},
		{
			Table:         "olap_export_retry_commands",
			RequiredBy:    "support-only OLAP retry/backfill idempotency command log",
			MigrationFile: "001_init.sql",
			Columns: []string{
				"command_id", "stream", "mode", "reason", "accepted", "checkpoint_before",
				"retry_requested_at", "pending_count", "failed_count", "created_at",
			},
			Indexes: []string{"olap_export_retry_commands_stream_created"},
		},
		{
			Table:         "olap_backfill_jobs",
			RequiredBy:    "async OLAP backfill jobs outside HTTP request path",
			MigrationFile: "001_init.sql",
			Columns: []string{
				"id", "command_id", "stream", "status", "requested_from", "requested_to",
				"checkpoint_cursor", "batch_size", "total_rows", "processed_rows", "last_error",
				"cancel_requested", "reason", "requested_by", "locked_by", "locked_at",
				"created_at", "started_at", "completed_at", "updated_at",
			},
			Indexes: []string{"olap_backfill_jobs_stream_status_created"},
		},
		{
			Table:         "olap_operator_audit_events",
			RequiredBy:    "operator audit trail for mutating OLAP controls",
			MigrationFile: "001_init.sql",
			Columns: []string{
				"id", "command_id", "action", "stream", "job_id", "requested_by", "reason", "created_at",
			},
			Indexes: []string{"olap_operator_audit_events_job_created"},
		},
		{
			Table:         "cloud_sync_problem_events",
			RequiredBy:    "cloudsync postgres repository problem item quarantine",
			MigrationFile: "001_init.sql",
			Columns: []string{
				"id", "direction", "node_device_id", "restaurant_id", "client_item_id", "error_code",
				"error_message", "raw_payload", "raw_payload_sha256_hex", "created_at",
			},
			Indexes: []string{"cloud_sync_problem_events_created_at"},
		},
		{
			Table:         "cloud_operational_events",
			RequiredBy:    "cloudsync postgres repository ReceiveEdgeEvent operational journal",
			MigrationFile: "001_init.sql",
			Columns: []string{
				"id", "receipt_id", "idempotency_key", "restaurant_id", "device_id", "command_id", "event_id", "edge_event_id",
				"event_type", "aggregate_type", "aggregate_id", "envelope_version", "occurred_at", "cloud_received_at",
				"raw_payload_sha256_hex", "replay_status", "created_at",
			},
			Indexes: []string{
				"cloud_operational_events_edge_event_key", "cloud_operational_events_type_received_at", "cloud_operational_events_restaurant_sequence",
			},
		},
		{
			Table:         "cloud_projection_event_type_stats",
			RequiredBy:    "cloudsync postgres repository applyEventProjections event type stats upsert",
			MigrationFile: "001_init.sql",
			Columns: []string{
				"restaurant_id", "device_id", "event_type", "event_count", "first_occurred_at", "last_occurred_at",
				"last_cloud_received_at", "last_event_id", "last_command_id", "updated_at",
			},
		},
		{
			Table:         "cloud_projection_shift_finance",
			RequiredBy:    "cloudsync postgres repository applyEventProjections shift finance upsert",
			MigrationFile: "001_init.sql",
			Columns: []string{
				"restaurant_id", "device_id", "shift_id", "payments_captured_count", "payments_captured_total",
				"payments_refunded_count", "payments_refunded_total", "checks_created_count", "checks_total_amount",
				"checks_refunded_count", "checks_refunded_total", "last_event_id", "last_command_id",
				"last_occurred_at", "last_cloud_received_at", "updated_at",
			},
		},
		{
			Table:         "cloud_projection_financial_operations",
			RequiredBy:    "cloudsync postgres repository detailed CancellationRecorded/RefundRecorded reporting projection",
			MigrationFile: "001_init.sql",
			Columns: []string{
				"operation_id", "edge_operation_id", "event_id", "receipt_id", "restaurant_id", "device_id",
				"node_device_id", "client_device_id", "actor_employee_id", "session_id",
				"shift_id", "original_shift_id", "check_id", "precheck_id", "operation_type", "operation_kind",
				"amount", "currency", "business_date_local", "inventory_disposition", "reason",
				"created_by_employee_id", "approved_by_employee_id", "snapshot_json",
				"operation_created_at", "occurred_at", "cloud_received_at", "raw_payload_sha256_hex", "created_at",
			},
			Indexes: []string{
				"cloud_projection_financial_operations_edge_operation",
				"cloud_projection_financial_operations_restaurant_date_type",
				"cloud_projection_financial_operations_shift",
				"cloud_projection_financial_operations_original_shift",
				"cloud_projection_financial_operations_check",
			},
		},
		{
			Table:         "cloud_master_data_packages",
			RequiredBy:    "cloudsync postgres repository master data package storage",
			MigrationFile: "001_init.sql",
			Columns: []string{
				"stream_name", "node_device_id", "restaurant_id", "sync_mode", "full_snapshot_reason", "cloud_version", "checkpoint_token",
				"cloud_updated_at", "payload_json", "created_at", "updated_at",
			},
			Indexes: []string{"cloud_master_data_packages_stream_updated"},
		},
		{
			Table:         "cloud_currency_reference",
			RequiredBy:    "cloudsync postgres startup currency reference catalog",
			MigrationFile: "001_init.sql",
			Columns: []string{
				"currency_code", "currency_alpha_code", "minor_unit", "currency_iso_name", "currency_symbol",
				"curr_basic_name", "curr_add_name", "show_add", "show_currency_basic_name", "active", "created_at", "updated_at",
			},
			Indexes: []string{"cloud_currency_reference_alpha_code_idx"},
		},
		{
			Table:         "cloud_restaurants",
			RequiredBy:    "cloud restaurant onboarding and master-data restaurants publication",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "name", "timezone", "currency", "business_day_mode", "business_day_boundary_local_time", "status", "cloud_version", "archived_at", "created_at", "updated_at"},
			Indexes:       []string{"cloud_restaurants_status_updated"},
		},
		{
			Table:         "cloud_roles",
			RequiredBy:    "cloud master-data authority role storage",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "name", "permissions_json", "active", "cloud_version", "archived_at", "created_at", "updated_at"},
		},
		{
			Table:         "cloud_employees",
			RequiredBy:    "cloud master-data authority employee lifecycle and PIN credential storage",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "role_id", "name", "status", "pin_hash", "pin_credential_version", "permission_snapshot_json", "cloud_version", "suspended_at", "archived_at", "created_at", "updated_at"},
			Indexes:       []string{"cloud_employees_restaurant_status"},
		},
		{
			Table:         "cloud_categories",
			RequiredBy:    "cloud master-data authority menu category storage",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "name", "status", "sort_order", "created_at", "updated_at"},
			Indexes:       []string{"cloud_categories_restaurant_status"},
		},
		{
			Table:         "cloud_catalog_items",
			RequiredBy:    "cloud master-data authority catalog item storage",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "kind", "folder_id", "name", "sku", "base_unit", "kitchen_type", "accounting_category", "status", "cloud_version", "archived_at", "created_at", "updated_at"},
			Indexes:       []string{"cloud_catalog_items_restaurant_kind_status", "cloud_catalog_items_active_sku"},
		},
		{
			Table:         "cloud_dishes",
			RequiredBy:    "cloud catalog dish foundation",
			MigrationFile: "001_init.sql",
			Columns:       []string{"catalog_item_id", "restaurant_id", "recipe_policy", "updated_at"},
		},
		{
			Table:         "cloud_goods",
			RequiredBy:    "cloud catalog goods foundation",
			MigrationFile: "001_init.sql",
			Columns:       []string{"catalog_item_id", "restaurant_id", "stock_tracking_mode", "updated_at"},
		},
		{
			Table:         "cloud_services",
			RequiredBy:    "cloud catalog service foundation",
			MigrationFile: "001_init.sql",
			Columns:       []string{"catalog_item_id", "restaurant_id", "fixed_unit", "updated_at"},
		},
		{
			Table:         "cloud_catalog_folders",
			RequiredBy:    "cloud catalog folder hierarchy",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "parent_id", "name", "sort_order", "status", "created_at", "updated_at"},
		},
		{
			Table:         "cloud_catalog_folder_parameters",
			RequiredBy:    "cloud catalog folder inherited parameters",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "folder_id", "parameter_key", "value_type", "value_json", "created_at", "updated_at"},
		},
		{
			Table:         "cloud_catalog_tags",
			RequiredBy:    "cloud catalog analytic tags",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "name", "code", "status", "created_at", "updated_at"},
		},
		{
			Table:         "cloud_catalog_item_tags",
			RequiredBy:    "cloud catalog item tag assignments",
			MigrationFile: "001_init.sql",
			Columns:       []string{"catalog_item_id", "tag_id", "restaurant_id", "created_at"},
		},
		{
			Table:         "cloud_semi_finished_products",
			RequiredBy:    "cloud catalog semi-finished products foundation",
			MigrationFile: "001_init.sql",
			Columns:       []string{"catalog_item_id", "restaurant_id", "production_unit", "updated_at"},
		},
		{
			Table:         "cloud_recipe_items",
			RequiredBy:    "cloud recipe foundation",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "recipe_owner_catalog_item_id", "component_catalog_item_id", "quantity", "unit", "loss_percent", "created_at", "updated_at"},
		},
		{
			Table:         "cloud_recipe_versions",
			RequiredBy:    "cloud scenario recipe version editor/review",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "owner_catalog_item_id", "version", "name", "status", "yield_quantity", "yield_unit", "created_by_employee_id", "submitted_by_employee_id", "approved_by_employee_id", "submitted_at", "approved_at", "created_at", "updated_at"},
			Indexes:       []string{"cloud_recipe_versions_owner_status", "cloud_recipe_versions_one_active"},
		},
		{
			Table:         "cloud_recipe_lines",
			RequiredBy:    "cloud scenario recipe version editor lines",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "recipe_version_id", "component_catalog_item_id", "quantity", "unit", "loss_percent", "sort_order", "created_at", "updated_at"},
			Indexes:       []string{"cloud_recipe_lines_version_order"},
		},
		{
			Table:         "cloud_modifier_groups",
			RequiredBy:    "cloud menu modifier group foundation",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "name", "status", "required", "min_count", "max_count", "created_at", "updated_at"},
		},
		{
			Table:         "cloud_modifier_options",
			RequiredBy:    "cloud menu modifier option foundation",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "modifier_group_id", "linked_catalog_item_id", "name", "price_minor", "status", "created_at", "updated_at"},
		},
		{
			Table:         "cloud_modifier_group_bindings",
			RequiredBy:    "cloud modifier binding foundation",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "modifier_group_id", "target_type", "target_id", "sort_order", "status", "created_at", "updated_at"},
		},
		{
			Table:         "cloud_menu_items",
			RequiredBy:    "cloud master-data authority menu item storage",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "catalog_item_id", "category_id", "name", "price", "currency", "status", "availability_json", "station_routing_key", "cloud_version", "archived_at", "created_at", "updated_at"},
			Indexes:       []string{"cloud_menu_items_restaurant_status"},
		},
		{
			Table:         "cloud_halls",
			RequiredBy:    "cloud floor master-data publication",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "name", "status", "cloud_version", "archived_at", "created_at", "updated_at"},
			Indexes:       []string{"cloud_halls_active_name"},
		},
		{
			Table:         "cloud_tables",
			RequiredBy:    "cloud floor master-data publication",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "hall_id", "name", "seats", "status", "cloud_version", "archived_at", "created_at", "updated_at"},
			Indexes:       []string{"cloud_tables_active_name"},
		},
		{
			Table:         "cloud_menu_item_modifier_groups",
			RequiredBy:    "future cloud menu modifier assignment foundation",
			MigrationFile: "001_init.sql",
			Columns:       []string{"menu_item_id", "modifier_group_id", "sort_order"},
		},
		{
			Table:         "cloud_menu_location_assignments",
			RequiredBy:    "future multi-location menu assignment foundation",
			MigrationFile: "001_init.sql",
			Columns:       []string{"menu_item_id", "location_id", "active"},
		},

		{
			Table:         "stock_documents",
			RequiredBy:    "cloud inventory foundation immutable stock document header",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "warehouse_id", "document_type", "source_event_id", "source_event_type", "business_date_local", "occurred_at", "created_at"},
			Indexes:       []string{"stock_documents_restaurant_occurred_at", "stock_documents_restaurant_warehouse_occurred_at", "stock_documents_source_event_unique"},
		},
		{
			Table:         "inventory_event_queue",
			RequiredBy:    "Cloud Inventory Worker durable queue for accepted Edge inventory events",
			MigrationFile: "001_init.sql",
			Columns: []string{
				"id", "receipt_id", "restaurant_id", "warehouse_id", "device_id", "event_id", "event_type", "aggregate_type", "aggregate_id",
				"status", "attempts", "next_retry_at", "locked_at", "locked_by", "processed_at", "last_error",
				"occurred_at", "created_at", "updated_at",
			},
			Indexes: []string{"inventory_event_queue_status_retry", "inventory_event_queue_event_type", "inventory_event_queue_restaurant_warehouse_order"},
		},
		{
			Table:         "stock_ledger",
			RequiredBy:    "cloud inventory foundation immutable stock movement and costing ledger",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "warehouse_id", "stock_document_id", "source_event_id", "source_event_type", "catalog_item_id", "order_line_id", "movement_type", "quantity", "unit_code", "unit_cost_minor", "total_cost_minor", "costing_status", "occurred_at", "business_date_local", "created_at"},
			Indexes:       []string{"stock_ledger_restaurant_occurred_at", "stock_ledger_restaurant_warehouse_occurred_at", "stock_ledger_source_event", "stock_ledger_order_line_consumption"},
		},
		{
			Table:         "stock_recalculation_jobs",
			RequiredBy:    "cloud inventory foundation retrospective recalculation queue",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "source_document_id", "status", "recalculate_from", "created_at", "updated_at"},
			Indexes:       []string{"stock_recalculation_jobs_restaurant_status"},
		},
		{
			Table:         "cloud_projection_stop_list_updates",
			RequiredBy:    "async StopListUpdated projection without raw payload exposure",
			MigrationFile: "001_init.sql",
			Columns:       []string{"source_event_id", "queue_id", "restaurant_id", "device_id", "stop_list_id", "warehouse_id", "catalog_item_id", "available_quantity", "active", "conflict_policy", "source", "reason", "projection_action", "review_status", "review_comment", "reviewed_by_employee_id", "reviewed_at", "assigned_to_employee_id", "assigned_by_employee_id", "assigned_at", "assignment_note", "applied_stop_list_id", "updated_at", "occurred_at", "projected_at", "created_at"},
			Indexes:       []string{"cloud_projection_stop_list_updates_restaurant_updated", "cloud_projection_stop_list_updates_action"},
		},
		{
			Table:         "stop_lists",
			RequiredBy:    "cloud authoritative stop-list state for sale blocking",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "catalog_item_id", "available_quantity", "source", "reason", "active", "cloud_version", "updated_at"},
			Indexes:       []string{"stop_lists_restaurant_item"},
		},
		{
			Table:         "cloud_pricing_policies",
			RequiredBy:    "cloud-owned discount/surcharge pricing policy reference",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "kind", "name", "scope", "amount_kind", "amount_minor", "value_basis_points", "application_index", "manual", "requires_permission", "status", "cloud_version", "archived_at", "created_at", "updated_at"},
			Indexes:       []string{"cloud_pricing_policies_restaurant_active"},
		},
		{
			Table:         "cloud_master_data_publications",
			RequiredBy:    "cloud master-data publication versioning and package generation",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "version", "status", "cloud_version", "published_at", "published_by", "package_json", "package_sha256", "created_at", "updated_at"},
			Indexes:       []string{"cloud_master_data_publications_current"},
		},
		{
			Table:         "cloud_catalog_suggestions",
			RequiredBy:    "cloud kitchen proposal review queue catalog suggestions",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "suggestion_id", "restaurant_id", "catalog_item_id", "proposal_group_id", "action", "reason", "status", "review_comment", "reviewed_by_employee_id", "reviewed_at", "assigned_to_employee_id", "assigned_by_employee_id", "assigned_at", "assignment_note", "applied_catalog_item_id", "source_event_id", "suggested_at", "cloud_received_at", "payload_json", "created_at", "updated_at"},
		},
		{
			Table:         "cloud_recipe_suggestions",
			RequiredBy:    "cloud kitchen proposal review queue recipe suggestions",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "suggestion_id", "restaurant_id", "recipe_version_id", "owner_catalog_item_id", "owner_catalog_suggestion_id", "proposal_group_id", "action", "reason", "prep_time_delta_minutes", "status", "review_comment", "reviewed_by_employee_id", "reviewed_at", "assigned_to_employee_id", "assigned_by_employee_id", "assigned_at", "assignment_note", "source_event_id", "suggested_at", "cloud_received_at", "payload_json", "created_at", "updated_at"},
		},
		{
			Table:         "cloud_recipe_suggestion_changes",
			RequiredBy:    "cloud kitchen recipe proposal diff rows",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "recipe_suggestion_id", "line_id", "action", "from_catalog_item_id", "to_catalog_item_id", "quantity", "unit_code", "loss_percent", "sort_order", "payload_json", "created_at"},
		},
		{
			Table:         "cloud_suggestion_review_events",
			RequiredBy:    "cloud kitchen proposal feedback stream source",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "suggestion_kind", "suggestion_id", "status", "reviewed_by_employee_id", "review_comment", "reviewed_at", "created_at"},
		},
		{
			Table:         "cloud_review_assignment_audit_events",
			RequiredBy:    "append-only assignment audit read for stop-list, catalog, and recipe review items",
			MigrationFile: "001_init.sql",
			Columns:       []string{"event_id", "command_id", "review_type", "review_id", "action", "actor_employee_id", "target_employee_id", "reason", "occurred_at"},
			Indexes:       []string{"cloud_review_assignment_audit_events_review_created"},
		},
		{
			Table:         "cloud_edge_nodes",
			RequiredBy:    "cloud edge device provisioning",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "restaurant_id", "node_device_id", "display_name", "status", "credentials_hash", "last_seen_at", "assigned_at", "revoked_at", "created_at", "updated_at"},
			Indexes:       []string{"cloud_edge_nodes_restaurant_status"},
		},
		{
			Table:         "cloud_unassigned_edge_nodes",
			RequiredBy:    "cloud edge device pending approval queue",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "node_device_id", "claimed_cloud_url", "display_name", "app_version", "status", "first_seen_at", "last_seen_at", "assigned_restaurant_id", "assigned_at", "created_at", "updated_at"},
			Indexes:       []string{"cloud_unassigned_edge_nodes_status_seen"},
		},
		{
			Table:         "cloud_pairing_codes",
			RequiredBy:    "cloud license server pairing code registration",
			MigrationFile: "001_init.sql",
			Columns:       []string{"id", "pairing_code_hash", "restaurant_id", "node_device_id", "cloud_url", "status", "expires_at", "consumed_at", "created_at", "updated_at"},
			Indexes:       []string{"cloud_pairing_codes_restaurant_status"},
		},
	}
}
